SAIL:=./vendor/bin/sail

up:
	${SAIL} up -d

down:
	${SAIL} down

sql:
	${SAIL} mysql

logs:
	${SAIL} logs

sail-install:
	docker run --rm \
		-u "$$(id -u):$$(id -g)" \
		-v "$$(pwd):/var/www/html" \
		-w /var/www/html \
		laravelsail/php83-composer:latest \
		composer install --ignore-platform-reqs
